import type { LibraryItem } from './types'

export const DEFAULT_LIBRARY_ITEMS = [
  {
    id: 1,
    title: 'The Hidden Life of Forests',
    type: 'Article',
    detail: '12 unfamiliar words',
    state: '68% read',
    cover: 'forests',
    vocabularyCount: 12,
    openedOrder: 1,
  },
  {
    id: 2,
    title: 'A Walk in the Woods',
    type: 'Story',
    detail: '8 unfamiliar words',
    state: 'Not started',
    cover: 'walk',
    vocabularyCount: 8,
    openedOrder: 4,
  },
  {
    id: 3,
    title: 'Why We Remember Words',
    type: 'Video',
    detail: '18 min',
    state: 'In progress',
    cover: 'video',
    vocabularyCount: 0,
    openedOrder: 2,
  },
  {
    id: 4,
    title: 'Learning Notes: Nature',
    type: 'Note',
    detail: '24 highlighted words',
    state: 'Edited today',
    cover: 'note',
    vocabularyCount: 24,
    openedOrder: 0,
  },
  {
    id: 5,
    title: 'The Language Habit',
    type: 'Podcast',
    detail: '32 min',
    state: 'Completed',
    cover: 'podcast',
    vocabularyCount: 0,
    openedOrder: 3,
  },
  {
    id: 6,
    title: 'The Secret Network Beneath Trees',
    type: 'Article',
    detail: '15 unfamiliar words',
    state: 'Saved Aug 12',
    cover: 'roots',
    vocabularyCount: 15,
    openedOrder: 5,
  },
] satisfies LibraryItem[]
